package org.nmjava.chatapp.commons.enums;

// #TODO: Add type request and response
public enum ResponseType {
    // User
    AUTHENTICATION,
    CREATE_ACCOUNT,
    FORGOT_PASSWORD,
    CHECK_USER_EXIST,
    //

    // Friend
    GET_LIST_FRIEND,
    GET_LIST_FRIEND_ONLINE,
    GET_LIST_REQUEST_FRIEND,
    UNFRIEND,
    ADD_FRIEND,
    ACCEPT_REQUEST_FRIEND,
    REJECT_REQUEST_FRIEND,
    //

    // Conservation
    GET_LIST_CONSERVATION,
    GET_LIST_MESSAGE_CONSERVATION,
    SEND_MESSAGE,
    DELETE_MESSAGE,
    SEARCH_MESSAGE_CONSERVATION,
    SEARCH_MESSAGE_ALL,
    // Group chat
    CREATE_GROUP_CHAT,
    GET_LIST_MEMBER_CONSERVATION,
    RENAME_GROUP_CHAT,
    ADD_MEMBER_GROUP_CHAT,
    GIVE_ADMIN_USER_GROUP_CHAT,
    REMOVE_USER_GROUP_CHAT,
    //
}
